### ISSUE TITLE
404 error on Deploys tab

### ISSUE THREAD

**Issue by Amet13** [zapic0/deployer#2]
Hello, @Zapic0! Thanks for great plugin.

I installed a plugin like this:
```
cd /var/www/redmine/plugins
git clone https://github.com/zapic0/deployer
bundle exec rake redmine:plugins NAME=deployer RAILS_ENV=production
```

And added info to deploy settings:
![screenshot at 2017-03-20 17-51-26](https://cloud.githubusercontent.com/assets/5184847/24105429/e96b7752-0d95-11e7-9468-d2edda846b48.png)

Then i tried to enter to tab "Deploys" and I see 404 error:
![screenshot at 2017-03-20 17-45-50](https://cloud.githubusercontent.com/assets/5184847/24105329/8c787f04-0d95-11e7-832e-58f4df18eabb.png)

How can I fix it?
Thanks.

**Comment by zapic0** [comment]
Hi Amet,

Thanks for your mail.

This sounds really strange, on fact you should see "deploys" even without
set the project settings.

I suppose you've already restarted your redmine server, didn't you?

I'd try to run plugin migrations:
rake redmine:plugins:migrate

And finally, try to create a new deploy by browsing to:
redmineserver.xxxxxxxx.xxx/projects/devops_admin/deploys/new

Please tell me if this works and, if it doesn't, take a look at redmine log
and share the errors with me to fix it ;)

Thanks!

2017-03-20 15:54 GMT+01:00 Amet Umerov <notifications@github.com>:

**Comment by Amet13** [comment]
Yes, I restarted server again. No effect.
On `redmine.domain.com/projects/devops_admin/deploys/new` i see "Internal error".

Redmine log for `projects/devops_admin/deploys/new`:
```
Started GET "/projects/devops_admin/deploys/new" for 195.123.209.46 at 2017-03-20 13:15:12 -0400
Processing by DeploysController#new as HTML
  Parameters: {"project_id"=>"devops_admin"}
  Current user: amet (id=32)
  Rendered plugins/deployer/app/views/deploys/new.html.erb within layouts/base (2.1ms)
Completed 500 Internal Server Error in 6.3ms

ActionView::Template::Error (undefined method `model_name' for NilClass:Class):
    1: <h2><%= t('.new_deploy') %></h2>
    2: 
    3: <%= form_for @deploy, url: { action: "create" }, builder: (defined? TabularFormBuilder) ? TabularFormBuilder : Redmine::Views::LabelledFormBuilder do |f| %>
    4: 
    5:   <div class="box tabular">
    6: 
  activemodel (3.2.21) lib/active_model/naming.rb:163:in `model_name_from_record_or_class'
  activemodel (3.2.21) lib/active_model/naming.rb:158:in `param_key'
  actionpack (3.2.21) lib/action_view/helpers/form_helper.rb:369:in `form_for'
  plugins/deployer/app/views/deploys/new.html.erb:3:in `_plugins_deployer_app_views_deploys_new_html_erb__1859706240063861438_70290369572900'
  actionpack (3.2.21) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.21) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.21) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
  actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:18:in `render'
  actionpack (3.2.21) lib/action_view/renderer/renderer.rb:36:in `render_template'
  actionpack (3.2.21) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:110:in `_render_template'
  actionpack (3.2.21) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:103:in `render_to_body'
  actionpack (3.2.21) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.21) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /srv/ruby/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
  activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `ms'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:39:in `render'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.21) lib/active_support/callbacks.rb:491:in `_run__316807394630164007__process_action__1139723903608044863__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__3530841638437285003__call__3314809942764246915__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in `call'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
  /srv/passenger/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /srv/passenger/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /srv/passenger/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /srv/passenger/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```

And for `projects/devops_admin/deploys/`:
```
Started GET "/projects/devops_admin/deploys" for 195.123.209.46 at 2017-03-20 13:16:36 -0400
Processing by DeploysController#index as HTML
  Parameters: {"project_id"=>"devops_admin"}
  Current user: amet (id=32)
  Rendered plugins/deployer/app/views/deploys/index.html.erb within layouts/base (2.9ms)
Completed 500 Internal Server Error in 7.8ms

ActionController::RoutingError (No route matches {:action=>"new", :controller=>"deploys", :project_id=>nil}):
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:540:in `raise_routing_error'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:536:in `rescue in generate'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:528:in `generate'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:569:in `generate'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:594:in `url_for'
  actionpack (3.2.21) lib/action_dispatch/routing/url_for.rb:148:in `url_for'
  actionpack (3.2.21) lib/action_view/helpers/url_helper.rb:107:in `url_for'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:216:in `new_project_deploy_path'
  plugins/deployer/app/views/deploys/index.html.erb:6:in `_plugins_deployer_app_views_deploys_index_html_erb__1368576248261473853_70290371712900'
  actionpack (3.2.21) lib/action_view/template.rb:145:in `block in render'
  activesupport (3.2.21) lib/active_support/notifications.rb:125:in `instrument'
  actionpack (3.2.21) lib/action_view/template.rb:143:in `render'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
  actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:54:in `render_with_layout'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
  actionpack (3.2.21) lib/action_view/renderer/template_renderer.rb:18:in `render'
  actionpack (3.2.21) lib/action_view/renderer/renderer.rb:36:in `render_template'
  actionpack (3.2.21) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:110:in `_render_template'
  actionpack (3.2.21) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:103:in `render_to_body'
  actionpack (3.2.21) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.21) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
  /srv/ruby/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
  activesupport (3.2.21) lib/active_support/core_ext/benchmark.rb:5:in `ms'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:39:in `render'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (3.2.21) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.21) lib/active_support/callbacks.rb:491:in `_run__316807394630164007__process_action__431178572814340257__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.21) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.21) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.21) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.21) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.21) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.21) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.21) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.21) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.21) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.21) lib/action_dispatch/routing/route_set.rb:608:in `call'
  rack-openid (1.4.2) lib/rack/openid.rb:98:in `call'
  request_store (1.0.5) lib/request_store/middleware.rb:9:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.5) lib/rack/etag.rb:23:in `call'
  rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.21) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.21) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `_run__3530841638437285003__call__3314809942764246915__callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.21) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.21) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.21) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.21) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.5) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.21) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.5) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/static.rb:83:in `call'
  rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
  rack-cache (1.2) lib/rack/cache/context.rb:245:in `fetch'
  rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
  rack-cache (1.2) lib/rack/cache/context.rb:66:in `call!'
  rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
  railties (3.2.21) lib/rails/engine.rb:484:in `call'
  railties (3.2.21) lib/rails/application.rb:231:in `call'
  railties (3.2.21) lib/rails/railtie/configurable.rb:30:in `method_missing'
  /srv/passenger/lib/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
  /srv/passenger/lib/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
  /srv/passenger/lib/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
  /srv/passenger/lib/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'
```

**Comment by zapic0** [comment]
It seems like redmine isn't loading correctly the project (and it can't pass project identifier to new deploy path).

What redmine version are you using? I'm trying to reproduce the problem but I wasn't lucky for now :(

**Comment by Amet13** [comment]
Version 2.6.1.

**Comment by Amet13** [comment]
Hi. Are you tested it on this Redmine version?
I tested it on 3.2, it works, but can't find any working docker image with redmine 2.6 for testing.

**Comment by zapic0** [comment]
Hi Amet, I haven't tested it in 2.6 yet, I'll try it ASAP but didn't find time yet 8-)

**Comment by Amet13** [comment]
Thanks!

**Comment by Amet13** [comment]
Hello.
I tested it on clean Redmine 2.6 from [here](https://github.com/sameersbn/docker-redmine/tree/2.6-stable).
Same story. So I think plugin does not work on this redmine's version.
Error in log the same.
![screenshot at 2017-04-10 12-46-10](https://cloud.githubusercontent.com/assets/5184847/24856013/f36fd994-1deb-11e7-956f-84c6162820a6.png)

**Comment by zapic0** [comment]
Hi Amet.

I guess so, I didn't test it in a version previous to 3.x (https://www.redmine.org/plugins/deployer).

I've been quite busy and this seems like "more than 2 hours of work" so I'll try to fix it but don't know when (hopefully soon). I'll try to tell you something by the end of this week ;)

Thanks for your help!!!
